# Generated by Django 5.2.12 on 2026-07-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastereport',
            name='ai_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wastereport',
            name='ai_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
