# Generated by Django 5.2.12 on 2026-07-24 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_wastereport_ai_category_wastereport_ai_confidence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wastereport',
            name='ai_category',
        ),
    ]
